### ISSUE TITLE
NegativeArraySizeException error on particular CFS file

### ISSUE THREAD

**Issue by tremby** [mjwoodcock/riscosarc#10]
I'm getting this traceback on a particular file:

```
java.lang.NegativeArraySizeException: -256
java.lang.NegativeArraySizeException: -256
        at riscos.archive.CFSInputStream.setBitSize(CFSInputStream.java:196)
        at riscos.archive.CFSInputStream.readCFSBlock(CFSInputStream.java:209)
        at riscos.archive.CFSInputStream.read(CFSInputStream.java:341)
        at riscosarc.main(riscosarc.java:194)
```

The file in question is zipped here. I'm not sure if the file is corrupt or this points to a bug.

[Text.zip](https://github.com/mjwoodcock/riscosarc/files/4794446/Text.zip)

**Comment by philpem** [comment]
This got my attention as I've been poking around in the Riscosarc extraction code - I don't have many CFS samples though, so thanks for breaking it!

This is a bit of both - the code expects the CFS end terminator to be four null bytes (ENDBLOCK, code limit low, code limit high, new byte). This file has two bytes - ENDBLOCK and one further null. If you stick two extra null bytes on the end, it should decode fine.

The bug is that the code doesn't handle EOF correctly, but if there's an EOF in an ENDBLOCK then obviously we've decoded all the compressed data and the EOF ceases to be relevant. So this could be handled better.

The output file is filetype &D88, an Impression "Stories" file, length 53384, which matches the CFS file header. Unfortunately my copies of Publisher and Impression II won't load it: it seems to be part of an Impression application-document, so is unreadable without the !DocData file.

I've opened a PR (#13) with a fix for this.
@tremby, does this decompress your Impression document correctly?

**Comment by tremby** [comment]
Oof unfortunately I have no idea which file I was trying to access 6 years ago! It was certainly one of my dad's old files but I don't have access to the NAS all that is on at this moment so I can't do a checksum search or something. I've been meaning to dig around for some other old files on that NAS and when I can (that is, when a family member remembers to turn on the NAS for me -- I'm in a different country) I'll try to remember to take a look.

In the mean time, if that fix allows that file I attached to decompress, and the output looks like it's probably a valid Stories file, then I expect your fix was a success, so thank you.
